//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCenter.MDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MDService.IMarketDataService")]
    public interface IMarketDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetHS300Weight", ReplyAction="http://tempuri.org/IMarketDataService/GetHS300WeightResponse")]
        System.Data.DataSet GetHS300Weight(System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetIndexPrices", ReplyAction="http://tempuri.org/IMarketDataService/GetIndexPricesResponse")]
        System.Data.DataSet GetIndexPrices(System.DateTime startDate, System.DateTime endDate, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetStockPrices", ReplyAction="http://tempuri.org/IMarketDataService/GetStockPricesResponse")]
        System.Data.DataSet GetStockPrices(System.DateTime startDate, System.DateTime endDate, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetAShareStockList", ReplyAction="http://tempuri.org/IMarketDataService/GetAShareStockListResponse")]
        System.Data.DataSet GetAShareStockList(string code, string exchange, string charIsST, string charIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetChinaBondList", ReplyAction="http://tempuri.org/IMarketDataService/GetChinaBondListResponse")]
        System.Data.DataSet GetChinaBondList(string code, string exchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetSWIndustryList", ReplyAction="http://tempuri.org/IMarketDataService/GetSWIndustryListResponse")]
        System.Data.DataSet GetSWIndustryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetFreeFloatCapital", ReplyAction="http://tempuri.org/IMarketDataService/GetFreeFloatCapitalResponse")]
        System.Data.DataSet GetFreeFloatCapital(System.DateTime endDate, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketDataService/GetTradingDays", ReplyAction="http://tempuri.org/IMarketDataService/GetTradingDaysResponse")]
        System.Data.DataSet GetTradingDays(System.DateTime startDate, System.DateTime endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketDataServiceChannel : ReportCenter.MDService.IMarketDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketDataServiceClient : System.ServiceModel.ClientBase<ReportCenter.MDService.IMarketDataService>, ReportCenter.MDService.IMarketDataService {
        
        public MarketDataServiceClient() {
        }
        
        public MarketDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetHS300Weight(System.DateTime endDate) {
            return base.Channel.GetHS300Weight(endDate);
        }
        
        public System.Data.DataSet GetIndexPrices(System.DateTime startDate, System.DateTime endDate, string code) {
            return base.Channel.GetIndexPrices(startDate, endDate, code);
        }
        
        public System.Data.DataSet GetStockPrices(System.DateTime startDate, System.DateTime endDate, string code) {
            return base.Channel.GetStockPrices(startDate, endDate, code);
        }
        
        public System.Data.DataSet GetAShareStockList(string code, string exchange, string charIsST, string charIsActive) {
            return base.Channel.GetAShareStockList(code, exchange, charIsST, charIsActive);
        }
        
        public System.Data.DataSet GetChinaBondList(string code, string exchange) {
            return base.Channel.GetChinaBondList(code, exchange);
        }
        
        public System.Data.DataSet GetSWIndustryList() {
            return base.Channel.GetSWIndustryList();
        }
        
        public System.Data.DataSet GetFreeFloatCapital(System.DateTime endDate, string code) {
            return base.Channel.GetFreeFloatCapital(endDate, code);
        }
        
        public System.Data.DataSet GetTradingDays(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetTradingDays(startDate, endDate);
        }
    }
}
